{
 "title": "Etcd",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(etcd_mvcc_db_total_size_in_bytes)/3",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "leader变更",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wal Fsync(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le)))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "DB Fsync ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    },
    {
     "expr": "avg(histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le)))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "Applied"
    }
   ]
  },
  {
   "title": "Client Traffic Recevied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Client Traffic Send",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "gRPC stream message(times/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_received_total[5m]))",
     "legendFormat": "Reveviced"
    },
    {
     "expr": "sum(rate(grpc_server_msg_sent_total[5m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}